[package]
name = "z3t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = {version="0.12.1", features = ["static-link-z3"]}
itertools = "0.11.0"
comfy-table = "7.0.1"